print('what is the height of your wall in feet?')
height = int(input())
print('what is the width of your wall in feet?')
width = int(input())
print('what is the average price of a gallon of paint?')
cost_of_paint = float(input())
wall = int(height * width)
gallons_of_paint_per_wall = float(wall / 400)
print(gallons_of_paint_per_wall)
print(cost_of_paint)
total_cost = round(float(gallons_of_paint_per_wall * cost_of_paint) , 2)
print(total_cost)
print('how many walls do you have to paint?')
num_walls = int(input())
cost_per_room = round(float(total_cost * num_walls) , 2)
print(cost_per_room)
